### ISSUE TITLE
SWAV: Larc 

### ISSUE THREAD

**Issue by whyrv** [KeremTurgutlu/self_supervised#15]
nice work. It looks like the 'official' implementation uses the Larc optimizer (and of course the Queue of qs). Have you tried that? It must be possible to enable that quite trivially here, is it not?

**Comment by KeremTurgutlu** [comment]
Thanks. I didn't implement any optimizer since fastai already has them implemented. In Imagewang benchmarks I used Ranger optimizer:

```
sqrmom=0.99
mom=0.95
beta=0.
eps=1e-4
opt_func = partial(ranger, mom=mom, sqr_mom=sqrmom, eps=eps, beta=beta)
```

Queue or memory banks in general is an idea from MOCO and used in SwaV as well as you mentioned. It's my to do list. It should potentially help when more number of protocols are needed. I initially tried without it and still manage to get best results on Imagewang laederboard.

**Comment by whyrv** [comment]
cool. look forward to the queue implementation. I think it is needed to be formally correct regardless of the current results you get:
__"Working with small batches. When the number B of batch features is too small compared to
the number of prototypes K, it is impossible to equally partition the batch into the K prototypes.
Therefore, when working with small batches, we use features from the previous batches to augment
..."_
It looks like a trivial port from their implementation but I'm not too sure if naive implementation will impact some metrics like runtime or numerical stability. The official implementation relies rather heavily on Apex.

**Comment by KeremTurgutlu** [comment]
Will definitely incorporate it in the coming weeks!
